# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60)),
                ('ApellidoPaterno', models.CharField(max_length=50)),
                ('ApellidoMaterno', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=150)),
                ('Telefono', models.CharField(max_length=15)),
                ('Correo', models.CharField(max_length=15, null=True)),
                ('FechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoCamion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=4)),
                ('ingreso', models.DateTimeField(auto_now_add=True)),
                ('cambio', models.DateTimeField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroUnidad', models.CharField(max_length=5)),
                ('FechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60)),
                ('Telefono', models.CharField(max_length=15)),
                ('Direccion', models.CharField(max_length=100)),
                ('FechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=80)),
                ('Turno', models.CharField(blank=True, choices=[('M', 'Matutino'), ('V', 'Vespertino')], max_length=1, null=True)),
                ('FechaAlta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroPago', models.CharField(max_length=5)),
                ('FechaPago', models.DateTimeField(auto_now_add=True)),
                ('Alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.Alumno')),
            ],
        ),
        migrations.AddField(
            model_name='camion',
            name='Chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.Chofer'),
        ),
        migrations.AddField(
            model_name='camion',
            name='Escuela',
            field=models.ManyToManyField(to='transporte.Escuela'),
        ),
        migrations.AddField(
            model_name='alumnocamion',
            name='camion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.Camion'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='Camion',
            field=models.ManyToManyField(related_name='camiones', through='transporte.AlumnoCamion', to='transporte.Camion'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='Escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transporte.Escuela'),
        ),
    ]
